### ISSUE TITLE
安装完都不能正常使用

### ISSUE THREAD

**Issue by hryGithub** [apioak/apioak#162]
![image](https://user-images.githubusercontent.com/32188410/78961123-ed62c880-7b22-11ea-95de-c704b5f9c7bb.png)
注册后台就报错
系统是centos7,mysql5.7

**Comment by shuaijinchao** [comment]
你好 安装之后需要把 /usr/local/apioak/conf/apioak.sql 基础数据结构导入数据库中 导入后 并修改 /usr/local/apioak/conf/apioak.yaml 配置文件后重启即可。

**Comment by hryGithub** [comment]
![image](https://user-images.githubusercontent.com/32188410/78965796-a8459300-7b30-11ea-831a-50488c36a1c3.png)数据库导入好了，配置文件也改好了

**Comment by shuaijinchao** [comment]
图片不能正常加载，方便留下你的联系方式吗？

**Comment by hryGithub** [comment]
qq：2917518534

**Comment by shuaijinchao** [comment]
已加请确认

**Comment by hryGithub** [comment]
没有收到好友请求，我的qq昵称Flying

**Comment by shuaijinchao** [comment]
QQ：97242666，加我一下吧。
