### ISSUE TITLE
产品使用上的一些疑问

### ISSUE THREAD

**Issue by pureliumy** [apioak/apioak#164]
1. 目前的路由添加需要手动一个个添加，是否考虑swagger、yapi之类的接口导入；
2. 项目的API是否考虑生成独立的文档页面，以及api返回示例支持代码高亮；
3. 没有发现Mock功能的入口。

**Comment by shuaijinchao** [comment]
@pureliumy 首先非常感谢你的反馈，你的问题我逐个回答一下。
1、目前API是需要手动添加的后面一定会考虑批量导入的功能，方便用户快速迁移。
2、目前在API列表中操作一栏有“详情”这个即API文档，不过后期考虑会增加文档导出功能可以快速向客户或使用方分发。
3、关于Mock请求API添加之后在如果API未发布访问的数据即Mock数据，也就是在添加API时第三步配置的响应数据，当API发布后即访问的是上游的应用数据。
