### ISSUE TITLE
路由配置，总是出问题

### ISSUE THREAD

**Issue by zhuewizz** [apioak/apioak#179]
你好：
  我下载了docker版的，跑起来了，我后台也跑了另一个docker
后台转发的配置，试了好久，跑不起来，有否有更详细的文档
关于参数配置的说明和例子？我的一个项目，正想用apioak,
我用的postgrest,希望统一前端的api

参数名 | 参数位置 | 参数类型 | 默认值 | 必填 | 备注 |  
-- | -- | -- | -- | -- | -- | --

**Comment by zanehy** [comment]
https://blog.csdn.net/hong_Y_yan/article/details/105402391
你好，可以先看下这个文档的 “项目管理” 和 “路由管理” 章节中的参数配置教程，有问题可以随时提到 issues 中。
感谢您的支持和使用，希望回答能帮助到您。

**Comment by zhuewizz** [comment]
我用的你们docker版，没有Path，等你们更新了，我再试试
