### ISSUE TITLE
v0.6.0 版本数据面重构设计

### ISSUE THREAD

**Issue by blust** [apioak/apioak#195]
## 概要设计
- 数据存储引擎由MariaDB更换为Consul
- 重新设计基础对象（服务、路由、插件、上游、节点、证书等）的数据结构
- 内存数据更新机制优化
- Admin-api 重构

## Admin-api 详细设计
- [服务相关设计](https://github.com/apioak/apioak/issues/192)
- [路由相关设计](https://github.com/apioak/apioak/issues/193)
- [插件相关设计](https://github.com/apioak/apioak/issues/194)
- [上游相关设计](https://github.com/apioak/apioak/issues/196)
- [节点相关设计](https://github.com/apioak/apioak/issues/197)
- [证书相关设计](https://github.com/apioak/apioak/issues/198)

## 内存数据 详细设计
- [内存数据&更新机制设计]()

**Comment by swtseaman** [comment]
请问新版本预计什么时候发布
是否具备根据请求头、请求体内容等判断用户身份并将请求转发到不同环境
如： header 有  user_type=pre  则将请求打到预发布   user_type=test 则将请求打到测试
如： 请求内容里包含用户A的账号，则将请求打到预发布

**Comment by zanehy** [comment]
> 

您好，目前咱们这本版本预计是在元旦前后进行发布，咱们这一版重新设计了整个架构，目前开发接近尾声了。
您说的这个能力目前在当前的基础版本内还没有支持到，不过您说的这个咱们的规划当中是有的，下期的版本发布也不会太远，我们会对您说的这种需求进行升级改造，也就是内容会更丰富更好用。
感谢您一直以来的关注，您的关注就是给我们最大的动力，我们会尽力做到更好。
在此也随时欢迎您给我们提出宝贵的意见和您更好的想法。

**Comment by swtseaman** [comment]
嗯，很期待你们的新版本，我现在的项目很需要一个可配置化的网关，灰度测试、发布是我们现在急需的东西；所以如果0.6的第一个版本发布后，我是否可以通过插件形式自行扩展这些自定义路由规则；另外插件是否是热插拔和修改实时生效的

**Comment by swtseaman** [comment]
另外请问有没有插件的开发文档

**Comment by zanehy** [comment]
> 

咱们的插件是热插拔的，修改后实时生效，同时咱们也支持多域名配置了，根据自己的需要增加您自己的服务域名即可，而且系统中几乎所有的配置都是热更新且修改后实时生效，包括多域名，路由，插件，等等。
目前插件还没有一个完整的开发文档，毕竟这是重构后的第一个基础版本，开发文档后续会进行及时的补充。

**Comment by swtseaman** [comment]
那请问我提的header body的条件+环境路由，你说在规划中，是系统做原生支持，还是以插件方式实现呢？有没有大概的时间点

**Comment by zanehy** [comment]
> 

目前规划的是您提的这种一般是以插件的形式来实现，并且以目前的规划会在基础版发布后的一个月后发布下一个版本，具体的时间还要根据具体的实际情况来定，版本迭代的时间间隔不会太久。

**Comment by swtseaman** [comment]
请问插件是可以给用户自由修改、自由扩展的吗

**Comment by zanehy** [comment]
> 请问插件是可以给用户自由修改、自由扩展的吗

插件是单独的功能模块，会有多个插件，每个插件都是一个不同的功能模块，插件内配置什么参数是有限制的，具体参数值配置什么是可由用户自由选择或者输入的，在指定的路由上或者服务上增加一个或者多个插件这个也是由用户来自由操作的。

**Comment by swtseaman** [comment]
我的意思是，插件是否是设计成可以在后台动态修改代码，来实现更多自定义功能

**Comment by zanehy** [comment]
> 我的意思是，插件是否是设计成可以在后台动态修改代码，来实现更多自定义功能
目前的插件没有设计成这样开放式的，这个还得根据后续的综合情况来衡量是否要加上这种功能。

**Comment by zanehy** [comment]
> 我的意思是，插件是否是设计成可以在后台动态修改代码，来实现更多自定义功能

目前的插件没有设计成这样开放式的，这个还得根据后续的综合情况来衡量是否要加上这种功能。
