### ISSUE TITLE
与apisix的区别是什么呢？

### ISSUE THREAD

**Issue by zzqCh** [apioak/apioak#205]

**Comment by zanehy** [comment]
您好，APISIX和Kong都是优秀的开源API网关，APIOAK更专注七层流量的调度并且提供了更人性化的控制平台，降低上手难度和运维成本，后续我们也会结合更多业务场景来丰富APIOAK的平台能力，感谢关注。

**Comment by zanehy** [comment]
您好，APISIX和Kong都是优秀的开源API网关，APIOAK更专注七层流量的调度并且提供了更人性化的控制平台，降低上手难度和运维成本，后续我们也会结合更多业务场景来丰富APIOAK的平台能力，感谢关注。
