### ISSUE TITLE
四层协议的代理与解析

### ISSUE THREAD

**Issue by zzqCh** [apioak/apioak#214]
您好，是否支持四层协议的代理与解析呢？比如自定义的rpc协议，需要解析协议的数据

**Comment by zanehy** [comment]
> 您好，是否支持四层协议的代理与解析呢？比如自定义的rpc协议，需要解析协议的数据

您好，目前咱们项目还没有支持四层协议，后面会有四层协议功能支持的计划，感谢您的关注！
